name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login Docker Hub
      run: docker login -u daniel0208 -p Pedropaulo123!

    - name: Build Docker Image
      run: docker build -t daniel0208/app-inventor .

    - name: Push imagem Docker
      run: docker push daniel0208/app-inventor
  
  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from Docker Hub
        run: docker pull ddaniel0208/app-inventor:latest

      - name: Remover container antigo (se existir)
        run: docker rm -f app-inventor || true

      - name: Subir o container
        run: docker run -d --name app-inventor -p 8080:80 daniel0208/app-inventor:latest
